version: '3.8'

services:
  app:
    build: .
    container_name: projectPHP
    volumes:
      - ./:/var/www/html   # Código fonte na pasta /var/www/html do container
      - ./composer_cache:/tmp # Cache do composer para acelerar downloads
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql          # Persistência dos dados
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ""
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - "8080:80"                         # Acesso via localhost:8080
    networks:
      - backend

volumes:
  mysql_data:
    name: projectecommerce_mysql_data
  composer_cache:

networks:
  backend:
    name: projectphp_network
