version: '3.8'

services:
  app:
    build: .
    container_name: projectPHP
    volumes:
      - ./:/var/www/html   # Código fonte na pasta /var/www/html do container
      - ./composer_cache:/tmp # Cache do composer para acelerar downloads
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: project_php
      MYSQL_USER: admin
      MYSQL_PASSWORD: "admin"
    volumes:
      - mysql_data:/var/lib/mysql          # Persistência dos dados

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "8080:80"                         # Acesso via localhost:8080

volumes:
  mysql_data:
  composer_cache:
